export const SET_GLOBAL = 'SET_GLOBAL';
export const IS_LOGGING_IN = 'IS_LOGGING_IN';
export const FETCH_ALL_INVESTMENTS = 'FETCH_ALL_INVESTMENTS';
export const IS_FETCHING_INVESTMENTS = 'IS_FETCHING_INVESTMENTS';
export const SET_ALL_INVESTMENTS = 'SET_ALL_INVESTMENTS';
